apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
data:
  FORESIGHT_BACKEND_URL: {{ .Values.env.foresight_backend_url | quote }}
  GIT_CLI_PROTOCOL: {{ .Values.env.git.git_cli_protocol | quote }}
  GIT_SERVIER_URL: {{ .Values.env.git.git_server_url | quote }}
  GIT_LOCAL_DIR: {{ .Values.env.git.git_local_dir | quote }}
  KEYCLOAK_REALM: {{ .Values.env.keycloak.keycloak_realm | quote }}
  KEYCLOAK_AUTH_SERVER_URL: {{ .Values.env.keycloak.keycloak_auth_server_url | quote }}
  KEYCLOAK_RESOURCE: {{ .Values.env.keycloak.keycloak_resource | quote }}


