apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      - name: {{ .Values.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.persistentVolumeClaim }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{ end }}
      containers:
      - name: {{ .Values.container.name }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        image: {{ .Values.container.image }}
        args: ["--app.cors.allowed-origins[0]={{ .Values.env.keycloak.keycloak_allowed_origins_1 }}",
        "--app.cors.allowed-origins[1]=http://localhost:4200",
        "--keycloak.enabled=true",
        "--keycloak.auth-server-url={{ .Values.env.keycloak.keycloak_auth_server_url }}",
        "--keycloak.ssl-required=none",
        "--keycloak.realm={{ .Values.env.keycloak.keycloak_realm }}",
        "--keycloak.resource={{ .Values.env.keycloak.keycloak_resource }}",
        "--keycloak.bearer-only=true",
        "--keycloak.autodetect-bearer-only=true",
        "--keycloak.enable-basic-auth=false",
        "--keycloak.use-resource-role-mappings=false",
        "--keycloak.public-client=true",
        "--keycloak.principal-attribute=preferred_username"]
        envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
        envFrom:
          - secretRef:
              name: {{ .Values.name }}-secret
        ports:
        - containerPort: {{ .Values.container.containerPort }}
